bug fix - DI-25228 - Notification 1.2 - selected fields not shown
Pepperi-Addons/push-notifications pull request #188
Opened 2024-05-28 08:01 UTC by NoamPepperi

2024-06-06 08:21 UTC, liorSela commented on client-side/src/app/components/notifications-setup/users-list-setup/users-list-setup.component.ts
> +      const resourceFields = this.resourceFields.filter(field => !this.userListData.SelectionDisplayFields.map(field => field.FieldName).includes(field))
duplicated code in both of the if

2024-06-06 08:23 UTC, liorSela requested changes

2024-06-06 08:23 UTC, liorSela commented on client-side/src/app/components/notifications-setup/users-list-setup/users-list-setup.component.ts
> +    if (apiName == 'DisplayFieldsSelector') {
duplicated code in both of the if

2024-06-06 10:18 UTC, liorSela approved these changes

2024-06-16 21:02 UTC, simcha-waintrob approved these changes

2024-06-16 21:02 UTC, merged