bugfix- DI-27196 - Notification - notification should display notific…
Pepperi-Addons/push-notifications pull request #190
Opened 2024-05-28 10:18 UTC by NoamPepperi

…ation from the last 30 days

2024-06-06 08:34 UTC, liorSela requested changes

2024-06-06 08:34 UTC, liorSela commented on client-side/src/app/components/notification-block/notification-block.component.ts
> +  reduceDays(date: Date, days: number): Date {
if it is only removing days from current date, maybe you can create the new date in the function and not pass it as parameter

2024-06-06 11:11 UTC, simcha-waintrob requested changes

2024-06-06 11:14 UTC, NoamPepperi commented on server-side/services/notifications.service.ts
> +import split from 'just-split';
yes

2024-06-06 11:31 UTC, simcha-waintrob commented on client-side/src/app/components/notification-block/notification-block.component.ts
> +    this.notificationsList = await this.notificationsService.getNotifications(`UserUUID='${this.addonService.userUUID}' AND CreationDateTime>='${lastDate}'`);
change the names for more understanding.
const lastMonthDate: string = this.lastMonthDate()

if you want to move the logic into the getNotifications function, you should rename the function to getLastMonthNotifications

2024-06-16 21:04 UTC, simcha-waintrob approved these changes

2024-06-16 21:05 UTC, merged