Di 27754 support run flow from notifications page
Pepperi-Addons/push-notifications pull request #192
Opened 2024-06-04 12:26 UTC by NoamPepperi

2024-06-06 09:02 UTC, liorSela approved these changes

2024-06-20 13:27 UTC, simcha-waintrob requested changes

2024-06-20 13:27 UTC, simcha-waintrob commented on server-side/services/notifications.service.ts
> +                    "Source": "Webapp",
can't you do it like the "Read"?
"FlowData": notificationToSend.FlowData ?? undefined

2024-06-20 13:27 UTC, simcha-waintrob commented on server-side/services/notifications.service.ts
> -
you can do it like this:
FlowData: body.FlowData // Directly assigns FlowData if it exists

2024-06-24 08:12 UTC, simcha-waintrob approved these changes

2024-06-24 08:12 UTC, merged