Di 26418   allow to configure notifications count soft limit
Pepperi-Addons/push-notifications pull request #196
Opened 2024-06-20 11:02 UTC by NoamPepperi

2024-06-23 06:47 UTC, liorSela requested changes

2024-06-23 06:47 UTC, liorSela commented on client-side/src/app/services/notifications-setup.services.ts
> +        return this.addonService.pepGet(encodeURI(`/addons/api/${this.addonService.addonUUID}/api/notifications_soft_limt`)).toPromise();
typo in limit

2024-06-23 06:58 UTC, liorSela approved these changes

2024-06-24 13:05 UTC, simcha-waintrob approved these changes

2024-06-24 13:05 UTC, merged