Big title command
Pepperi-Addons/push-notifications pull request #201
Opened 2024-06-24 12:43 UTC by NoamPepperi

2024-06-26 13:37 UTC, liorSela commented on server-side/integration-tests/commands/big-title-command.ts
> +    BIG_TITLE_LENGTH: number = 51;
shouldn't it be 41 to make sure it is failing after 40 characters?

2024-06-30 08:07 UTC, liorSela approved these changes

2024-07-02 08:11 UTC, simcha-waintrob commented on server-side/integration-tests/commands/big-title-command.ts
> +    BIG_TITLE_LENGTH: number = 41;
If Product decides to change this number, the change will have to be made in several files.
and also to update the error message. - Complex.
To solve this, a constant must be defined with this number, and when they want to change it, the change will only be in one place.
both server-side, and client-side will use this constant
the same for BIG_MESSAGE_LENGTH

2024-07-02 09:09 UTC, simcha-waintrob requested changes

2024-07-02 09:09 UTC, simcha-waintrob commented on server-side/integration-tests/commands/big-title-command.ts
> +        expect(this.errMessage).to.equal("Failed due to exception: Title does not meet maximum length of 40");
change it also here - in the error message
make this message also a const, so that in case of changes, the change will be only in once place.
the same in MESSAGE_MAX_LENGTH

2024-07-02 09:46 UTC, merged